// internal/cli/daemon.go
package cli

import (
	"context"
	"fmt"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/spf13/cobra"
	"loop-eng/internal/budget"
	"loop-eng/internal/channel"
	"loop-eng/internal/daemon"
	"loop-eng/internal/loop"
	"loop-eng/internal/skill"
	"loop-eng/internal/state"
	"loop-eng/internal/verify"
)

// NewDaemonCmd builds `loop-eng daemon`: the resident loop engine (spec §8.3).
// It polls the ticket channel every --poll-interval, ingests new tasks, dispatches
// them one at a time (single-active, synchronous — spec §12: no concurrency), and
// parks/resumes tier-3 needs-review tasks. The daemon never blocks on a human
// (spec principle 7): tier-3 parks → releases the active slot → polls replies → resumes.
func NewDaemonCmd() *cobra.Command {
	var repo, channelFlag, models string
	var pollInterval, cooldown time.Duration
	cmd := &cobra.Command{
		Use:   "daemon",
		Short: "常驻 loop 引擎（轮询工单 + 单活跃子 loop + park/resume）",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg := mustLoad(repo)
			st := mustOpenState(repo)
			defer st.Close()

			if channelFlag != "" {
				cfg.Channel.Provider = channelFlag
			}
			ch, err := buildChannel(cfg, repo)
			if err != nil {
				return err
			}

			// Preflight gate (#65): refuse to start when the channel's
			// prerequisites are missing, with an actionable checklist — fail
			// fast at boot instead of crashing mid-run (e.g. a missing
			// loop:running label only surfacing when UpdateStatus hits it).
			if err := runPreflight(context.Background(), ch); err != nil {
				return err
			}

			// RunTask: construct a fresh SubLoop per dispatched task + run it.
			// SubLoop does the full plan→execute→verify→writeback (incl. channel
			// comment + status mark via report()). PreinsertedTaskID = the daemon's
			// already-ingested task ID (avoids duplicate InsertTask).
			runTask := func(ctx context.Context, task state.TaskRow) (string, string, error) {
				bz := budget.New(cfg.Budget.PerCallTokens, cfg.Budget.PerTaskTokens, cfg.Budget.MaxRetries)
				// 任务级 agent override：daemon 从 issue 摄取的 task.Agent 覆盖各角色 provider
				// （agent: codex → 该任务全程用 codex）。未知 provider 静默回落 config 默认。
				taskCfg := applyTaskAgent(cfg, task.Agent)
				exec, plan, verifySkill, _, help := buildModels(taskCfg, models, bz)

				// tier-1 不再从 config 接入——plan 每轮按任务产出验收脚本，SubLoop.tiersFor
				// 据此挂 tier-1（在当前 worktree 里跑）。无静态/兜底列表。
				sl := &loop.SubLoop{
					Repo:              repo,
					Store:             st,
					Budget:            bz,
					Execute:           exec,
					Plan:              plan,
					Help:              help,
					VerifyLLM:         verify.LLM{Skill: verifySkill},
					Tier3Human:        taskCfg.Verify.Tier3Human,
					Channel:           ch,
					PreinsertedTaskID: task.ID,
					PlanModelRef:      providerLabel(taskCfg.Models.Plan),
					ExecuteModelRef:   providerLabel(taskCfg.Models.Execute),
					VerifyModelRef:    providerLabel(taskCfg.Models.Verify),
					AgentForRole:      agentForRole(taskCfg),
				}

				ct := channel.Task{
					Ref:                task.IssueRef,
					Description:        task.Description,
					TaskType:           task.TaskType,
					AcceptanceCriteria: task.Criteria,
					Body:               task.Body, // 全文保留：plan/execute 的背景上下文
					CreatedAt:          task.CreatedAt,
				}
				out, err := sl.Run(ctx, ct)
				if err != nil {
					fmt.Fprintf(os.Stderr, "[daemon] task %s error: %v\n", task.ID, err)
					return "error", "", err
				}
				// Integrate done work: prefer a GitHub PR (push branch + gh pr create).
				// push 最终失败（ErrPushFailed）→ LAND PARTIAL：不 FF-merge 到本地
				// main（merge 进 push 不上去的 main 会制造本地分叉且 operator 无感知）、
				// 保留 branch+worktree 供手动 push，done detail 与 issue 评论都带
				// LAND PARTIAL 标记。其他 PR 失败（gh 侧）→ 既有本地 FF-merge 兜底；
				// land 失败（非 FF）保留 branch —— 工作不丢，只是集成延后。
				if out.Status == "done" && out.Branch != "" {
					prTitle := task.Description
					if prTitle == "" {
						prTitle = "loop-eng task #" + task.IssueRef
					}
					prBody := "Closes #" + task.IssueRef + "\n\nauto-generated by loop-eng"
					prURL, prErr := createPR(repo, cfg.Channel.Repo, out.Branch, out.Worktree, prTitle, prBody)
					if prErr != nil {
						logf := func(format string, args ...any) {
							fmt.Fprintf(os.Stderr, "[daemon] task "+task.ID+" "+format+"\n", args...)
						}
						if extra := handlePRFailure(ctx, ch, task.IssueRef, repo, out.Worktree, out.Branch, prErr, logf); extra != "" {
							out.Detail += "\n" + extra
						}
					} else {
						fmt.Printf("[daemon] task %s PR created: %s\n", task.ID, prURL)
						ch.PostComment(ctx, task.IssueRef, "PR: "+prURL)
					}
				}
				fmt.Printf("[daemon] task %s → %s\n", task.ID, out.Status)
				return out.Status, out.Detail, nil
			}

			// Triage 门：派发前对 FIFO 队首分诊（spec triage/gate）。buildModels 需要
			// 一个 Enforcer，但 triage 本身不走 budget（per-run 作用域，triage 在 run
			// 之前；一次小调用/次派发）——只为构建 skill 传一个独立的 Enforcer。
			_, _, _, triageSkill, _ := buildModels(cfg, models, budget.New(cfg.Budget.PerCallTokens, cfg.Budget.PerTaskTokens, cfg.Budget.MaxRetries))
			triageFn := func(ctx context.Context, task state.TaskRow) (skill.TriageOutput, error) {
				out, _, err := triageSkill.Run(ctx, skill.TriageInput{
					TaskDescription:    task.Description,
					AcceptanceCriteria: task.Criteria,
					TaskType:           task.TaskType,
					Body:               task.Body, // 全文：判断「缺不缺信息」以全文为准
				})
				return out, err
			}

			interval := pollInterval
			if cfg.Daemon.PollInterval > 0 {
				interval = cfg.Daemon.PollInterval
			}
			eng := &daemon.Engine{
				Channel:   ch,
				Store:     st,
				Interval:  interval,
				Cooldown:  cooldown,
				RunTask:   runTask,
				Triage:    triageFn,
				IngestMin: 3 * time.Second,
				IngestMax: 10 * time.Second,
			}
			// worktree 现场 GC：每 tick 一次（状态驱动 + 48h 宽限期；blocked 现场
			// 缓存按 SceneTTL 回收）。repo 路径在 CLI 层，故以闭包注入 engine。
			eng.GC = func(ctx context.Context) error {
				acts, err := loop.GCWorktrees(repo, st, loop.DefaultGCPolicy())
				if err != nil {
					return err
				}
				for _, a := range acts {
					if a.Delete {
						fmt.Printf("[daemon] gc: deleted %s (%s)\n", a.Name, a.Reason)
					}
				}
				return nil
			}

			ctx, cancel := context.WithCancel(context.Background())
			defer cancel()
			sigCh := make(chan os.Signal, 1)
			signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
			go func() {
				<-sigCh
				fmt.Fprintln(os.Stderr, "[daemon] shutting down...")
				cancel()
			}()

			fmt.Printf("[daemon] starting (poll=%s, channel=%s)\n", pollInterval, cfg.Channel.Provider)
			return eng.Run(ctx)
		},
	}
	cmd.Flags().StringVar(&repo, "repo", ".", "仓库路径")
	cmd.Flags().StringVar(&channelFlag, "channel", "", "local | github（空=用 cfg.Channel.Provider）")
	cmd.Flags().StringVar(&models, "models", "real", "real | fake")
	cmd.Flags().DurationVar(&pollInterval, "poll-interval", 60*time.Second, "轮询间隔")
	cmd.Flags().DurationVar(&cooldown, "cooldown", 5*time.Minute, "瞬时基础设施阻塞（如上游 529 限流）后的派发冷却时长")
	return cmd
}
