// internal/cli/run_once.go
package cli

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"loop-eng/internal/budget"
	"loop-eng/internal/channel"
	"loop-eng/internal/config"
	"loop-eng/internal/loop"
	"loop-eng/internal/model"
	"loop-eng/internal/skill"
	"loop-eng/internal/state"
	"loop-eng/internal/verify"
)

// NewRunOnceCmd builds `loop-eng run-once`: the M1 synchronous entry point.
// It loads .loop/config.yaml, opens .loop/state.db, assembles the model
// client (Fake under --models=fake, ClaudeClient otherwise — 裁决 I single
// claude-p path, no API/anthropic branch), builds the four skills + verify
// tier chain, wires a SubLoop, pulls the first inbox task, and prints the
// Outcome. Budget is enforced three ways (per-call / per-task / retries);
// verify's LLM Call is budget-wrapped via budget.Client to close the
// carry-forward gap from Task 12 (SubLoop budget-wraps plan+execute
// manually; that stays untouched — no double-count).
func NewRunOnceCmd() *cobra.Command {
	var repo, inbox, models, channelFlag string
	cmd := &cobra.Command{
		Use:   "run-once",
		Short: "M1 同步入口：从 inbox 捞一个任务跑完整 loop",
		RunE: func(cmd *cobra.Command, args []string) error {
			cfg := mustLoad(repo)
			st := mustOpenState(repo)
			defer st.Close()

			// --channel 非空则覆盖 cfg.Channel.Provider（命令行优先于 config）
			if channelFlag != "" {
				cfg.Channel.Provider = channelFlag
			}

			bz := budget.New(cfg.Budget.PerCallTokens, cfg.Budget.PerTaskTokens, cfg.Budget.MaxRetries)
			exec, plan, verifySkill, triage := buildModels(cfg, models, bz)
			_ = triage // M1 SubLoop 外分诊（M3 daemon 调用）

			ch, err := buildChannel(cfg, repo)
			if err != nil {
				return err
			}

			tasks, err := ch.ListNewTasks(context.Background())
			if err != nil || len(tasks) == 0 {
				return fmt.Errorf("no task in inbox %s", inbox)
			}
			// tier-1 不再从 config 接入——plan 每轮按任务产出验收脚本，SubLoop.tiersFor
			// 据此挂 tier-1（在当前 worktree 里跑）。无静态/兜底列表。
			sl := &loop.SubLoop{
				Repo:       repo,
				Store:      st,
				Budget:     bz,
				Execute:    exec,
				Plan:       plan,
				VerifyLLM:  verify.LLM{Skill: verifySkill},
				Tier3Human: cfg.Verify.Tier3Human,
				Channel:    ch,
			}
			out, err := sl.Run(context.Background(), tasks[0])
			// Integrate done work: prefer a GitHub PR, fall back to FF-merge.
			if err == nil && out.Status == "done" && out.Branch != "" {
				prTitle := tasks[0].Description
				if prTitle == "" {
					prTitle = "loop-eng task #" + tasks[0].Ref
				}
				prBody := "Closes #" + tasks[0].Ref + "\n\nauto-generated by loop-eng"
				prURL, prErr := createPR(repo, cfg.Channel.Repo, out.Branch, out.Worktree, prTitle, prBody)
				if prErr != nil {
					fmt.Fprintf(os.Stderr, "PR failed, fallback to FF-merge: %v\n", prErr)
					if lerr := land(repo, out.Worktree, out.Branch); lerr != nil {
						fmt.Fprintf(os.Stderr, "land failed (work safe on branch %s): %v\n", out.Branch, lerr)
						out.Detail += " [land failed: " + lerr.Error() + "]"
					} else {
						fmt.Printf("landed on main (branch %s)\n", out.Branch)
					}
				} else {
					fmt.Printf("PR created: %s\n", prURL)
				}
			}
			fmt.Printf("outcome: %s — %s\n", out.Status, out.Detail)
			return err
		},
	}
	cmd.Flags().StringVar(&repo, "repo", ".", "仓库路径")
	cmd.Flags().StringVar(&inbox, "task-inbox", "", "任务 inbox 目录（用于错误提示；实际读 <repo>/inbox）")
	cmd.Flags().StringVar(&models, "models", "real", "real | fake（测试用）")
	cmd.Flags().StringVar(&channelFlag, "channel", "", "local | github（空=用 cfg.Channel.Provider）")
	return cmd
}

// buildChannel picks the channel.Channel by cfg.Channel.Provider: "" or
// "local" → channel.Local (reads <repo>/inbox, writes <repo>/outbox);
// "github" → channel.GitHub backed by the authenticated `gh` CLI;
// "linear" → channel.Linear backed by the Linear GraphQL API (key from env
// LOOP_ENG_LINEAR_API_KEY, per #24 决定 A — never from config.yaml). Unknown
// providers error. This is the M2-6 wiring point that replaces the M1
// hard-coded channel.NewLocal(repo).
func buildChannel(cfg *config.Config, repo string) (channel.Channel, error) {
	prov := cfg.Channel.Provider
	if prov == "" {
		prov = "local"
	}
	switch prov {
	case "local":
		ch := channel.NewLocal(repo)
		if cfg.Channel.Inbox != "" {
			ch.InboxDir = cfg.Channel.Inbox
		}
		return ch, nil
	case "github":
		return channel.NewGitHub(cfg.Channel.Repo, cfg.Channel.TaskLabel), nil
	case "linear":
		key := os.Getenv(channel.LinearAPIKeyEnv)
		if key == "" {
			return nil, fmt.Errorf("linear provider: 环境变量 %s 未设置", channel.LinearAPIKeyEnv)
		}
		// cfg.Channel.Linear 是指针（config 交互命令的产物）；validate() 已保证
		// provider=linear 时非 nil。
		lc := cfg.Channel.Linear
		return channel.NewLinear(key, "", lc.Project, lc.Team, lc.StatusMap), nil
	default:
		return nil, fmt.Errorf("unknown channel provider: %s", prov)
	}
}

// buildModels assembles the four skills' shared model.Client plus the typed
// Skill wrappers. mode="fake" wires a FakeClient keyed by prompt prefix (for
// CI/hermetic tests); otherwise a single ClaudeClient backs every role
// (spec §8.1 / 裁决 I — M1 simplifies plan/execute/verify to one claude -p
// path, no API branch, no anthropic SDK).
//
// The verify skill's Model is wrapped in a budget.Client sharing the SAME
// *Enforcer passed to SubLoop.Budget. This closes the Task 12 carry-forward
// gap: verify.Chain's frozen Tier interface takes no Enforcer, so without
// the decorator the verify LLM Call would bypass BeforeCall/AfterCall and
// its tokens would never accrue into spent (spec §8.8 deviation). plan and
// execute keep the raw client because SubLoop already budget-wraps those
// two manually — wrapping them again would double-count.
func buildModels(cfg *config.Config, mode string, bz *budget.Enforcer) (
	exec model.Executer,
	plan skill.Skill[skill.PlanInput, skill.PlanOutput],
	vs skill.Skill[skill.VerifyInput, skill.VerifyOutput],
	triage skill.Skill[skill.TriageInput, skill.TriageOutput],
) {
	if mode == "fake" {
		f := model.NewFake(map[string]string{
			"TRIAGE:":  jsonStr(skill.TriageOutput{Startable: true, LoopDoable: true}),
			"PLAN:":    jsonStr(skill.PlanOutput{Plan: []skill.PlanStep{{Step: "实现任务以满足验收标准"}}}),
			"EXECUTE:": "ok",
			"VERIFY:":  jsonStr(skill.VerifyOutput{Passed: true}),
		})
		exec = f
		plan = skill.Skill[skill.PlanInput, skill.PlanOutput]{Name: "plan", PromptTmpl: mustSkillPrompt("plan"), ParseJSON: parseJSON[skill.PlanOutput], Model: f}
		vs = skill.Skill[skill.VerifyInput, skill.VerifyOutput]{Name: "verify", PromptTmpl: mustSkillPrompt("verify"), ParseJSON: parseJSON[skill.VerifyOutput], Model: &budget.Client{Base: f, Enf: bz}}
		triage = skill.Skill[skill.TriageInput, skill.TriageOutput]{Name: "triage", PromptTmpl: mustSkillPrompt("triage"), ParseJSON: parseJSON[skill.TriageOutput], Model: f}
		return
	}
	// real: all via `claude -p` (no SDK, no API key). Each role uses claude's
	// default model unless its config sets `name` (→ --model <name>) as an opt-in
	// (e.g. a lighter model for plan/verify to ease a congested default). History:
	// direct-API (决策 J) rejected (needs key/SDK); alias-pinning (决策 K) rejected
	// (aliases drift); final = model-agnostic default + config-opt-in per role.
	exec = model.NewClaudeClient(cfg.Models.Execute.Binary, cfg.Models.Execute.Name, cfg.Models.Execute.Cmd)
	plan = skill.Skill[skill.PlanInput, skill.PlanOutput]{Name: "plan", PromptTmpl: mustSkillPrompt("plan"), ParseJSON: parseJSON[skill.PlanOutput], Model: model.NewClaudeClient(cfg.Models.Plan.Binary, cfg.Models.Plan.Name, cfg.Models.Plan.Cmd)}
	vs = skill.Skill[skill.VerifyInput, skill.VerifyOutput]{Name: "verify", PromptTmpl: mustSkillPrompt("verify"), ParseJSON: parseJSON[skill.VerifyOutput], Model: &budget.Client{Base: model.NewClaudeClient(cfg.Models.Verify.Binary, cfg.Models.Verify.Name, cfg.Models.Verify.Cmd), Enf: bz}}
	triage = skill.Skill[skill.TriageInput, skill.TriageOutput]{Name: "triage", PromptTmpl: mustSkillPrompt("triage"), ParseJSON: parseJSON[skill.TriageOutput], Model: model.NewClaudeClient(cfg.Models.Triage.Binary, cfg.Models.Triage.Name, cfg.Models.Triage.Cmd)}
	return
}

// mustSkillPrompt reads an embedded skill template (embed/skills/<name>.md) and
// panics on read failure. The embedded templates render ALL Input fields (spec
// §8.5) — notably verify.md carries AcceptanceCriteria + PriorFailureSignal, so
// the verifier sees the criteria it must judge against (§8.6 命门 — the old
// truncated "VERIFY: {{.Diff}}" literal omitted them). Each template begins with
// its role prefix (TRIAGE:/PLAN:/VERIFY:), so FakeClient's HasPrefix matching is
// preserved unchanged.
func mustSkillPrompt(name string) string {
	b, err := skillFiles.ReadFile("embed/skills/" + name + ".md")
	if err != nil {
		panic("read embedded skill " + name + ": " + err.Error())
	}
	return string(b)
}

func parseJSON[O any](b []byte) (O, error) {
	var o O
	return o, json.Unmarshal(b, &o)
}

func jsonStr(v any) string {
	b, _ := json.Marshal(v)
	return string(b)
}

// mustLoad reads <repo>/.loop/config.yaml. M1 simplification: load failure
// panics (run-once is a dev/test entry point; M3 daemon will surface errors
// via issue comments).
func mustLoad(repo string) *config.Config {
	c, err := config.Load(filepath.Join(repo, ".loop", "config.yaml"))
	if err != nil {
		panic(err)
	}
	return c
}

// mustOpenState opens <repo>/.loop/state.db. Same M1 panic-on-failure policy
// as mustLoad.
func mustOpenState(repo string) *state.Store {
	st, err := state.Open(filepath.Join(repo, ".loop", "state.db"))
	if err != nil {
		panic(err)
	}
	return st
}
